export type ProjectDoc = {
  projectId: string;
  uid: string;
  name: string;
  toolType: string;
  status: "pending" | "in_progress" | "completed";
  styleId?: string;
  outfitId?: string;
  backgroundId?: string;
  poseId?: string;
  gender?: string;
  purpose?: string;
  sourcePhotoUrl?: string;
  resultImageUrl?: string;
  brandingScore?: number;
  brandingStrengths?: string[];
  profileReviewData?: Record<string, unknown>;
  isFavorite: boolean;
  deletedAt?: Date | null;
  createdAt: Date;
  updatedAt: Date;
};
