export const PREMIUM_STATUSES = ["free", "active", "cancelled", "expired"] as const;
export const ACCOUNT_STATUSES = ["active", "suspended", "deleted"] as const;
export const LOGIN_PROVIDERS = ["email", "google", "apple", "facebook"] as const;

export type UserDoc = {
  uid: string;
  name: string;
  email: string;
  photoUrl?: string;
  loginProvider: (typeof LOGIN_PROVIDERS)[number];
  emailVerified: boolean;
  credits: number;
  passCredits: number;
  passExpiresAt?: Date | null;
  activePassId?: string | null;
  adRewardClaimed: boolean;
  isPremium: boolean;
  premiumPlanId?: string | null;
  premiumPlanName?: string | null;
  premiumStatus: (typeof PREMIUM_STATUSES)[number];
  premiumStartedAt?: Date | null;
  premiumExpiresAt?: Date | null;
  purchaseId?: string | null;
  accountStatus: (typeof ACCOUNT_STATUSES)[number];
  welcomeBonusGranted: boolean;
  fcmToken?: string | null;
  fcmPlatform?: string | null;
  createdAt: Date;
  updatedAt: Date;
  lastLoginAt?: Date | null;
  __v?: number;
};
